@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.hairuo.design.patterns.type.behavior.responsibilitychain.Client#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.hairuo.design.patterns.type.behavior.responsibilitychain.Client",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1224712708 { 
   	label=hairuo
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1447193104 { 
   	label=design
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1051213074 { 
   	label=Client
	labeljust=l
	fillcolor=white
	style=filled
   
   Client1157752907XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Client

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1604349063 { 
   	label=Handler
	labeljust=l
	fillcolor=white
	style=filled
   
   Handler1157752907XXXhandler104431[
	label="+ handler()"
	style=filled
	fillcolor=white
	tooltip="Handler

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_808301359 { 
   	label=ConcreteHandler1
	labeljust=l
	fillcolor=white
	style=filled
   
   ConcreteHandler11157752907XXXhandler104431[
	label="+ handler()"
	style=filled
	fillcolor=white
	tooltip="ConcreteHandler1

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_808301360 { 
   	label=ConcreteHandler2
	labeljust=l
	fillcolor=white
	style=filled
   
   ConcreteHandler21157752907XXXhandler104431[
	label="+ handler()"
	style=filled
	fillcolor=white
	tooltip="ConcreteHandler2

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_808301361 { 
   	label=ConcreteHandler3
	labeljust=l
	fillcolor=white
	style=filled
   
   ConcreteHandler31157752907XXXhandler104431[
	label="+ handler()"
	style=filled
	fillcolor=white
	tooltip="ConcreteHandler3

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Client1157752907XXXmain1859653459 -> Handler1157752907XXXhandler104431;
ConcreteHandler11157752907XXXhandler104431 -> Handler1157752907XXXhandler104431;
ConcreteHandler21157752907XXXhandler104431 -> Handler1157752907XXXhandler104431;
ConcreteHandler31157752907XXXhandler104431 -> Handler1157752907XXXhandler104431;
Handler1157752907XXXhandler104431 -> ConcreteHandler11157752907XXXhandler104431;
Handler1157752907XXXhandler104431 -> ConcreteHandler21157752907XXXhandler104431;
Handler1157752907XXXhandler104431 -> ConcreteHandler31157752907XXXhandler104431;
Handler1157752907XXXhandler104431 -> Handler1157752907XXXhandler104431;
    
}
@enduml